-- Seed template generated by scripts/upload-assets.mjs
-- Replace <PUBLIC_URL> with the actual URL produced in scripts/uploads.json

-- Example insert using a known product name
-- INSERT INTO public.products (name, description, price, category, stock, image_url)
-- VALUES ('Imported: hero-fitness', 'Imported asset hero-fitness.png', 0.0, 'Imported', 0, '<PUBLIC_URL>');

-- Example update for existing product by name
-- UPDATE public.products SET image_url = '<PUBLIC_URL>' WHERE name ILIKE '%hero-fitness%';
